Repository marketkarly-team/marketkarly-client, pull requests merged in 2023-02, with the labels that each got.

#30 Complete Best Product List Condition Section (#12)
  client/css/include/best_product_list.css
  client/page/include/best_product_list.html
Labels: ➕Add

#31 Complete Product Review Section (#15)
  client/css/include/product_review.css
  client/css/style.css
  client/page/include/product_review.html
Labels: ➕Add

#32 Complete Product Inquiry Section(#16)
  client/css/include/product_inquiry.css
  client/css/style.css
  client/page/include/product_inquiry.html
Labels: ➕Add

#33 Complete Footer (#6)
  client/css/include/footer.css
  client/page/include/footer.html
Labels: ➕Add

#37 Complete Product list#13
  client/css/include/product_list.css
  client/css/style.css
  client/page/include/product_list.html
Labels: 🖥️Feature

#38 Complete Header#4
  client/css/include/header.css
  client/page/include/header.html
Labels: ➕Add

#39 Add Top Banner & Popup Markup and CSS Stylesheet (#7)
  client/css/include/top_banner&popup.css
  client/page/include/popup.html
  client/page/include/top_banner&popup.html
Labels: ➕Add

#40 Add Product Detail Information Markup (#14)
  client/assets/icons/Icon/icon-alarm-off.png
  client/assets/icons/Icon/icon-alarm-on.png
  client/assets/icons/Icon/icon-heart-off.png
  client/assets/icons/Icon/icon-heart-on.png
  client/assets/product_detail/tangtang/detail_banner.jpg
  client/assets/product_detail/tangtang/detail_banner.png
  client/assets/product_detail/tangtang/detail_info.jpg
  client/assets/product_detail/tangtang/detail_info.png
  client/page/include/pd_detail_info.html
Labels: ➕Add

#42 Add Main page#9
  client/css/include/main.css
  client/css/style.css
  client/js/include/main.js
  client/page/include/main.html
Labels: 🖥️Feature

#43 Add Signup Markup (#11)
  client/css/common/a11y.css
  client/css/common/base.css
  client/css/include/signup.css
  client/css/style.css
  client/page/include/signup.html
Labels: ➕Add

#44 Add Login Markup (#10)
  client/css/common/base.css
  client/css/include/login.css
  client/css/style.css
  client/page/include/login.html
  client/page/login.html
Labels: ➕Add

#46 Add Modal Cart icon button in porduct list(#13)
  client/css/include/product_list.css
  client/page/include/product_list.html
Labels: ➕Add

#49 Complete Product Detail Information (#14)
  client/css/include/pd_detail_info.css
  client/page/include/pd_detail_info.html
Labels: ➕Add

#50 Refactoring files : Assemble pages #45
  client/css/common/base.css
  client/css/include/best.css
  client/css/include/footer.css
  client/css/include/product_list.css
  client/css/include/signup.css
  client/css/include/top_banner&popup.css
  client/css/style.css
  client/page/best.html
  client/page/cart.html
  client/page/home.html
  client/page/include/best_product_list.html
  client/page/include/deallist.html
  client/page/include/footer.html
  client/page/include/login.html
  client/page/login.html
  client/page/product_info.html
  client/page/signup.html
Labels: 🔮Refactor

#52 Refactor filter & reveiew & inquiry product list(#48)
  client/assets/product_detail/tangtang/detail_popup.png
  client/css/common/theme.css
  client/css/include/best_product_list.css
  client/css/include/inquiry_popup.css
  client/css/include/product_inquiry.css
  client/css/include/product_review.css
  client/css/include/review_popup.css
  client/page/include/best_product_list.html
  client/page/include/inquiry_popup.html
  client/page/include/product_inquiry.html
  client/page/include/product_review.html
  client/page/include/review_popup.html
Labels: 🔮Refactor

#53 Feature shopping-cart html and css (#17)
  client/assets/for_cart/product_cart.jpg
  client/css/include/cart.css
  client/css/include/signup.css
  client/css/style.css
  client/page/include/cart.html
Labels: 🖥️Feature

#57 Refactor filter reveiew inquiry list#48
  client/css/include/best_product_list.css
  client/css/include/inquiry_popup.css
  client/css/include/product_review.css
Labels: 😈Bug, 🔮Refactor

#58 Validation filter reveiew inquiry component(#48)
  client/css/include/product_inquiry.css
  client/css/include/product_review.css
  client/css/include/review_popup.css
  client/page/include/best_product_list.html
  client/page/include/inquiry_popup.html
  client/page/include/product_inquiry.html
  client/page/include/product_review.html
  client/page/include/review_popup.html
Labels: 🔮Refactor

#61 Refactoring files#45
  client/css/common/base.css
  client/css/include/best.css
  client/css/include/cart.css
  client/css/include/footer.css
  client/css/include/login.css
  client/css/include/main.css
  client/css/include/main_banner.css
  client/css/include/navigation.css
  client/css/include/pd_detail_info.css
  client/css/include/product_info.css
  client/css/include/product_inquiry.css
  client/css/include/product_list.css
  client/css/include/product_review.css
  client/css/include/signup.css
  client/css/include/top_banner&popup.css
  client/css/style.css
  client/index.html
  client/js/navigation.js
  client/js/swiper-main.js
  client/js/swiper-product-inquiry.js
  client/js/swiper-product-review.js
  client/page/best.html
  client/page/cart.html
  client/page/home.html
  client/page/include/cart.html
  client/page/include/main.html
  client/page/include/pd_detail_info.html
  client/page/include/product_inquiry.html
  client/page/include/product_review.html
  client/page/login.html
  client/page/product_info.html
  client/page/signup.html
Labels: 🔮Refactor

#67 Initialize JS Module Function & JSON Server (#66)
  client/js/include/navigation.js
  client/js/include/swiper-main.js
  client/js/include/swiper-product-inquiry.js
  client/js/include/swiper-product-review.js
  client/lib/dom/attr.js
  client/lib/dom/bindEvent.js
  client/lib/dom/clearContents.js
  client/lib/dom/controlElement.js
  client/lib/dom/css.js
  client/lib/dom/getInputValue.js
  client/lib/dom/getNode.js
  client/lib/dom/index.js
  client/lib/dom/insert.js
  client/lib/dom/makeArray.js
  client/lib/dom/showAlert.js
  client/lib/dom/userList.js
  client/lib/error/index.js
  client/lib/error/refError.js
  client/lib/error/syntaxError.js
  client/lib/error/typeError.js
  client/lib/index.js
  client/lib/math/getRandom.js
  client/lib/math/index.js
  client/lib/math/sum.js
  client/lib/utils/copy.js
  client/lib/utils/delay.js
  client/lib/utils/fetch.js
  client/lib/utils/index.js
  client/lib/utils/memo.js
  client/lib/utils/memoization.js
  client/lib/utils/storage.js
  client/lib/utils/theme.js
  client/lib/utils/tiger.js
  client/lib/utils/typeOf.js
  client/lib/utils/xhr.js
  server/db/data.json
Labels: 🌟Initial, ⚙️Setting

#77 Refactor product review&inquiry component(#76)
  client/css/include/product_inquiry.css
  client/js/include/swiper-product-inquiry.js
  client/js/include/swiper-product-review.js
  client/lib/utils/index.js
  client/lib/utils/swiper.js
  client/page/product_info.html
Labels: 👓A11Y, 🔮Refactor, ➕Add

#79 Refactor review&inquiry pop-up component by web accessibilty(#78)
  client/css/include/inquiry_popup.css
  client/css/include/review_popup.css
  client/page/include/inquiry_popup.html
  client/page/include/review_popup.html
Labels: 👓A11Y, 🔮Refactor

#85 Product List Filter Component with JS(#80)
  client/css/include/product_list_filter.css
  client/js/include/product_list_filter.js
  client/lib/dom/checkSelected.js
  client/lib/dom/index.js
  client/lib/dom/resetSelected.js
  client/page/best.html
Labels: 🖥️Feature, 🔮Refactor

#87 Add popup close function (#74)
  client/css/include/top_banner&popup.css
  client/js/include/banner_and_popup.js
  client/page/include/top_banner&popup.html
Labels: 🖥️Feature, ➕Add

#90 Add Navigation JS #68
  client/css/include/navigation.css
  client/js/include/navigation.js
  client/lib/dom/css.js
  client/page/home.html
Labels: 👓A11Y, 🖥️Feature, ➕Add

#92 Add Signup CSS and JS #70
  client/css/include/signup.css
  client/js/include/signup.js
  client/page/signup.html
Labels: 👓A11Y, 🖥️Feature, ➕Add

#95 Add navigation in all pages (#68)
  client/css/include/navigation.css
  client/js/include/navigation.js
  client/page/best.html
  client/page/cart.html
  client/page/login.html
  client/page/product_info.html
  client/page/signup.html
Labels: ➕Add

#98 Add Product list JS#63
  client/css/include/product_list.css
  client/index.html
  client/js/include/cart_modal.js
  client/js/include/product_list.js
  client/page/best.html
  client/page/include/cart__modal.html
Labels: ➕Add

#99 Fix product info tab re-position(#82)
  client/css/include/pd_detail_info.css
  client/page/product_info.html
Labels: 🔮Refactor

#101 Add review & inquiry pop-up component to product_info.html(#83)
  client/css/include/inquiry_popup.css
  client/css/include/review_popup.css
  client/js/include/review_inquiry.js
  client/page/include/inquiry_popup.html
  client/page/product_info.html
Labels: ➕Add

#102 Add Header JS#62
  client/css/include/header.css
  client/js/include/header.js
  client/page/best.html
  client/page/cart.html
  client/page/home.html
  client/page/login.html
  client/page/product_info.html
  client/page/signup.html
Labels: 👓A11Y, ➕Add

#103 Fix review&inquiry pop-up css & reassign image directory(#83)
  client/css/include/inquiry_popup.css
  client/css/include/review_popup.css
  client/page/product_info.html
Labels: 🔮Refactor

#105 Cart js#65
  client/css/include/cart.css
  client/js/include/cart.js
  client/page/cart.html
Labels: ➕Add

#110 Refactor main-banner swiper (#64)
  client/js/include/swiper_main_banner.js
  client/page/home.html
Labels: 🔮Refactor

#106 Add Main#81
  client/css/include/main.css
  client/css/include/modal_cart.css
  client/css/include/product_list.css
  client/css/style.css
  client/js/include/home_main.js
  client/js/include/swiper-main.js
  client/page/home.html
Labels: 👓A11Y, ➕Add

#114 Fix validation of Best Page
  client/assets/Karly.png
  client/assets/product_list/baby_laundry_detergent.webp
  client/assets/product_list/jyoleudi_sun_cushion.webp
  client/assets/product_list/milkyqueen_brown_rice.webp
  client/assets/product_list/tangtang_jjolmyeon.webp
  client/css/include/footer.css
  client/css/include/header.css
  client/css/include/product_list.css
  client/css/include/product_list_filter.css
  client/page/best.html
Labels: 😈Bug, 👓A11Y

#116 Fix Best markup#108
  client/css/include/product_list.css
  client/page/best.html
Labels: 👓A11Y

#115 Fix validation of Home#107
  client/assets/Karly.png
  client/assets/banner/banner1.jpg
  client/assets/banner/banner1.webp
  client/assets/banner/banner10.jpg
  client/assets/banner/banner10.webp
  client/assets/banner/banner11.jpg
  client/assets/banner/banner11.webp
  client/assets/banner/banner12.jpg
  client/assets/banner/banner12.webp
  client/assets/banner/banner13.jpg
  client/assets/banner/banner13.webp
  client/assets/banner/banner14.jpg
  client/assets/banner/banner14.webp
  client/assets/banner/banner15.jpg
  client/assets/banner/banner15.webp
  client/assets/banner/banner16.jpg
  client/assets/banner/banner16.webp
  client/assets/banner/banner17.jpg
  client/assets/banner/banner17.webp
  client/assets/banner/banner2.jpg
  client/assets/banner/banner2.webp
  client/assets/banner/banner3.jpg
  client/assets/banner/banner3.webp
  client/assets/banner/banner4.jpg
  client/assets/banner/banner4.webp
  client/assets/banner/banner5.jpg
  client/assets/banner/banner5.webp
  client/assets/banner/banner6.jpg
  client/assets/banner/banner6.webp
  client/assets/banner/banner7.jpg
  client/assets/banner/banner7.webp
  client/assets/banner/banner8.jpg
  client/assets/banner/banner8.webp
  client/assets/banner/banner9.jpg
  client/assets/banner/banner9.webp
  client/assets/main/card_banner.webp
  client/assets/main/melon_banner.webp
  client/assets/main/purple_banner.webp
  client/assets/main/sale_banner.webp
  client/assets/product_list/baby_laundry_detergent.jpg
  client/assets/product_list/baby_laundry_detergent.webp
  client/assets/product_list/jyoleudi_sun_cushion.jpg
  client/assets/product_list/jyoleudi_sun_cushion.webp
  client/assets/product_list/milkyqueen_brown_rice.jpg
  client/assets/product_list/milkyqueen_brown_rice.webp
  client/assets/product_list/tangtang_jjolmyeon.jpg
  client/assets/product_list/tangtang_jjolmyeon.webp
  client/css/include/header.css
  client/css/include/main_banner.css
  client/js/include/cart_modal.js
  client/js/include/header.js
  client/js/include/product_list.js
  client/js/include/swiper-main.js
  client/js/include/swiper_main_banner.js
  client/page/home.html
Labels: 😈Bug, 👓A11Y

#117 Fix validation and a11y of cart (#111)
  client/assets/for_cart/product_cart.webp
  client/css/common/theme.css
  client/css/include/cart.css
  client/css/include/footer.css
  client/css/include/product_list_filter.css
  client/page/cart.html
Labels: 😈Bug, 👓A11Y, 🔮Refactor

#112 Add Signup validation (password and email) signup#70
  client/css/include/signup.css
  client/js/include/signup.js
  client/page/login.html
  client/page/signup.html
Labels: 👓A11Y, ➕Add

#120 Add aside swiper JS Home#107
  client/js/include/home_main.js
  client/js/include/swiper-main.js
  client/js/include/swiper_aside.js
  client/page/home.html
Labels: ➕Add

#119 Feature ajax for user login&sing-in component(#104)
  client/css/include/signup.css
  client/js/include/login.js
  client/js/include/server.js
  client/js/include/signup.js
  client/lib/utils/fetch.js
  client/lib/utils/index.js
  client/lib/utils/randomText.js
  client/page/login.html
  client/page/signup.html
  server/db/data.json
Labels: 🖥️Feature

#122 Fix aside js error(#107)
  client/js/include/swiper_aside.js
  client/page/home.html
Labels: 😈Bug

#123 Ajax login#104
  client/css/include/signup.css
  client/js/include/login.js
  client/js/include/server.js
  server/db/data.json
Labels: 🖥️Feature, ➕Add
